use_frameworks!
target 'LAFramework_Example' do
  pod 'LAFramework', :path => '../'
  target 'LAFramework_Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs'
  end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "LAFramework"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
    require File.expand_path('runscript.rb', '../LAFramework')
    RunScriptConfigurator::post_install(installer)
end

