use_frameworks!
target 'LAFramework_Example' do
  pod 'LAFramework', :path => '../'
  target 'LAFramework_Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs'
  end
end


post_install do |installer|
    require File.expand_path('runscript.rb', '../LAFramework')
    RunScriptConfigurator::post_install(installer)
end


